#!/usr/sbin/nft -f

flush ruleset

table inet filter {

    chain input {
	# Base Input Policy
        type filter hook input priority 0; policy drop;
	
	# Дозволити вже встановлені зʼєднання
	ct state vmap { established : accept, related : accept, invalid : drop }
	
	# Allow SSH
        tcp dport ssh accept
	
	# Дозволити https
	tcp dport { http, https } accept
	udp dport { http, https } accept

	# Дозволити локальний інтерфейс
        iif "lo" accept
		
	# Дозволити пририєднання до wireguard
	udp dport { 51820, 51830 } accept
	
        #reject with icmp type port-unreachable
    }

    chain forward {
	
	# Base Forward Policy
        type filter hook forward priority 0; policy drop;
	
	# Дозволити вже встановлені зʼєднання
	ct state vmap { established : accept, related : accept, invalid : drop }	

	# Дозволити трафік на loopback
	iif "lo" accept
	
	# Allow VPN Connections VPN->ANY
	ip saddr 172.16.30.0/24 accept
    }

    chain output {
	
	# Політика за замовчуванням
        type filter hook output priority 0; policy accept;
    }

}

table ip nat {
    ct helper ftp-standard {
        type "ftp" protocol tcp;
    }

    ct helper sip-5060 {
        type "sip" protocol udp;
    }

    ct helper tftp-69 {
        type "tftp" protocol udp;
    }

    chain postrouting {
	type nat hook postrouting priority 100;
	ip saddr 172.16.30.0/24 oifname "eth0" masquerade
    }
}

table inet mangle {
    chain prerouting {
	type filter hook prerouting priority -150;
	
	# Mark traffic for user from VPN
	ip saddr 172.16.30.100 mark set 100
    }
}
